#' Make Plots
#'
#' Executes a sequence of three plotting functions: barchart of total annotations,
#' cumulative histogram of unique annotations, and a bubble chart of metabolite classes
#' derived from MS2Query data. Handles conditional loading of metadata and checks for
#' common quantification file spelling errors.
#'
#' @param final.annotation.df A data frame containing processed feature annotations.
#'   Must include 'feature.ID', 'Samples', and 'compound.name'.
#' @param folder Path to the main output directory where plots and data are saved
#'   and where 'ms2query/' and 'mzmine/' subdirectories are expected.
#' @param remove_sample Optional sample name to exclude from cumulative histogram analysis
#'   (e.g., crude). Defaults to NULL, meaning no sample is excluded.
#' @param ms2query_threshold MS2Query model prediction threshold (default 0.7).
#' @param noise_area_threshold Peak area threshold for quantification data (default 10000).
#'
#' @return A list containing the processed data frames generated by each plot function:
#'   'barchart_data', 'histogram_data', and 'bubblechart_data'.
#'
#' @export
#' @importFrom dplyr select rename mutate
make_plots <- function(
    final.annotation.df,
    folder,
    remove_sample = NULL,
    ms2query_threshold = 0.7,
    noise_area_threshold = 10000
) {

  # --- File Path Setup ---

  # 1. Check for Metadata file existence (case-sensitive)
  metadata_base_path <- "HGM/A - Analysis.csv"
  if (file.exists(metadata_base_path)) {
    metadata_file <- metadata_base_path
  } else {
    metadata_file <- NULL
    message("Metadata file 'HGM/A - Analysis.csv' not found. Barchart will use raw sample names.")
  }

  # 2. MS2Query file path
  ms2query_file <- paste0(folder, "/ms2query/ms2query.csv")

  # 3. Check for Quantification file existence (handling two common spellings)
  quant_file_base_1 <- paste0(folder, "/mzmine/DATA_iimn_gnps_quant.csv")
  quant_file_base_2 <- paste0(folder, "/mzmine/data_iimn_gnps_quant.csv") # lowercase d

  if (file.exists(quant_file_base_1)) {
    quant_file <- quant_file_base_1
  } else if (file.exists(quant_file_base_2)) {
    quant_file <- quant_file_base_2
  } else {
    quant_file <- NULL
    warning("Quantification file (DATA/data_iimn_gnps_quant.csv) not found in the mzmine folder. The bubble chart function will fail.")
  }

  # --- 1. BARCHART FUNCTION CALL ---

  message("\nStarting Barchart Generation (Feature Counts per Sample)...")
  # Assumes generate_feature_barchart is defined in the environment
  barchart_data <- generate_feature_barchart(
    final.annotation.df = final.annotation.df,
    folder = folder,
    metadata.path = metadata_file
  )

  # --- 2. CUMULATIVE HISTOGRAM FUNCTION CALL ---

  message("\nStarting Cumulative Histogram Generation (Unique Annotations per Fraction)...")

  # Re-create the 'Annotations.with.samples' input required by the histogram function
  Annotations.with.samples_input <- final.annotation.df %>%
    dplyr::select(feature.ID, Samples, compound.name) %>%
    dplyr::rename(annotation = compound.name) %>%
    dplyr::mutate(annotation = ifelse(is.na(annotation), 0, 1))

  # Assumes generate_cumulative_histogram is defined in the environment
  histogram_data <- generate_cumulative_histogram(
    Annotations.with.samples = Annotations.with.samples_input,
    folder = folder,
    remove_sample = remove_sample # Pass NULL if not provided
  )

  # --- 3. BUBBLE CHART FUNCTION CALL ---

  message("\nStarting Metabolite Class Bubble Chart Generation (MS2Query Data)...")

  if (is.null(quant_file)) {
    bubblechart_data <- NULL
    warning("Skipping bubble chart generation because the quantification file was not found.")
  } else if (!file.exists(ms2query_file)) {
    bubblechart_data <- NULL
    warning("Skipping bubble chart generation because the MS2Query file was not found.")
  } else {
    # Assumes generate_ms2query_bubblechart is defined in the environment
    bubblechart_data <- generate_ms2query_bubblechart(
      ms2query.path = ms2query_file,
      quant.data.path = quant_file,
      folder = folder,
      threshold = ms2query_threshold,
      noise_area_threshold = noise_area_threshold
    )
  }

  return(list(
    barchart_data = barchart_data,
    histogram_data = histogram_data,
    bubblechart_data = bubblechart_data
  ))

  # Step 4: Pre-flight File Deletion
  message("Checking for and deleting existing output files...")
  if (Sys.getenv("USER_DOMAIN") == "unimelb") {
    delete_if_exists(paste0(folder, "/final-annotation-df.csv"))
    delete_if_exists(paste0("Y:/MA_BPA_Microbiome/Dataset-Annotations/", dataset.id, ".csv"))
    delete_if_exists(paste0("Y:/MA_BPA_Microbiome/Dataset-Abundances/", dataset.id, "-samples-df.csv"))
    delete_if_exists(paste0("Y:/MA_BPA_Microbiome/Dataset-Abundances/", dataset.id, "-top-10-features.csv"))
  } else {
    delete_if_exists(paste0(folder, "/", dataset.id, ".csv"))
    delete_if_exists(paste0(folder, "/",dataset.id, "-samples-df.csv"))
    delete_if_exists(paste0(folder, "/", dataset.id, "-top-10-features.csv"))
    delete_if_exists(paste0(folder, "/", dataset.id, "/cytoscape-v2.csv"))
  }

  # Step 4: Writing all files
  message("Writing new files...")
  if (Sys.getenv("USER_DOMAIN") == "unimelb") {
    write_large_csv(final.annotation.df2, paste0(folder, "/final-annotation-df.csv"))
    write_large_csv(final.annotation.df2, paste0("Y:/MA_BPA_Microbiome/Dataset-Annotations/", dataset.id, ".csv"))
    write_large_csv(samples.df, paste0("Y:/MA_BPA_Microbiome/Dataset-Abundances/", dataset.id, "-samples-df.csv"))
    write_large_csv(top_10_features, paste0("Y:/MA_BPA_Microbiome/Dataset-Abundances/", dataset.id, "-top-10-features.csv"))
  } else {
    write_large_csv(final.annotation.df2, paste0(folder, "/", dataset.id, ".csv"))
    write_large_csv(samples.df, paste0(folder, "/",dataset.id, "-samples-df.csv"))
    write_large_csv(top_10_features, paste0(folder, "/", dataset.id, "-top-10-features.csv"))
  }
}
